language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
cache: cargo
before_script:
  - |
    mkdir -p $HOME/.local/bin/ &&
    curl -s -L -o $HOME/.local/bin/cargo-fmt https://github.com/woofwoofinc/rustfmt/releases/download/0.2.16/cargo-fmt.lnx64 &&
    chmod +x $HOME/.local/bin/cargo-fmt &&
    curl -s -L -o $HOME/.local/bin/rustfmt https://github.com/woofwoofinc/rustfmt/releases/download/0.2.16/rustfmt-lnx64 &&
    chmod +x $HOME/.local/bin/rustfmt &&
    export PATH=$HOME/.local/bin:$PATH

script:
  - |
    cargo fmt -- --write-mode=diff &&
    cargo build &&
    cargo test
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libssl-dev
